### ISSUE TITLE
Operator Dictionary: form

### ISSUE THREAD

**Issue by fred-wang** [Igalia/chromium-dev#16]
From the roadmap: form (for selecting an entry in the dictionary)

**Comment by rwlbuis** [comment]
Support is expected to be there, but tests need to be imported, which may show up new problems.

**Comment by fred-wang** [comment]
> Support is expected to be there, but tests need to be imported, which may show up new problems.

@rwlbuis Right, I plan to write more tests. In particular, related to #24 I wonder if the form is determined from the position of the core operator or of the embellished operator? I suspect we we'll have to move that determination from the DOM classes to the layout classes.
