### ISSUE TITLE
Operator Dictionary: accent, largeop and movablelimits

### ISSUE THREAD

**Issue by fred-wang** [Igalia/chromium-dev#17]
From the roadmap: accent, largeop and movablelimits (to perform spacing in under and over scripts)

**Comment by rwlbuis** [comment]
A lot of progress was made on these this week. It is hard to say when it is enough to close this issue, but as discussed we also need to make sure there are enough tests.

**Comment by fred-wang** [comment]
> A lot of progress was made on these this week. It is hard to say when it is enough to close this issue, but as discussed we also need to make sure there are enough tests.

I think this is essentially done but I'll review the spec/tests.

**Comment by fred-wang** [comment]
* largeop tests cover dictionary, draw bigger in displaystyle and parameters in underover/msubsup
* movablelimits tests cover for dictionary and layout change in underover
* accent tests cover dictionary and parameters in underover. I think we need probably need more tests, but the core spec is still underspecified regarding accents, so at least we have the desired basic support.

I think we can close this.
