### ISSUE TITLE
Stretchy Operators: Roots (msqrt, mroot)

### ISSUE THREAD

**Issue by fred-wang** [Igalia/chromium-dev#25]
It is put in "Stretchy Operators" in the roadmap because we need to stretch the radical symbol vertically. A first implementation could be to use a scale transform on 'SQUARE ROOT' (U+221A) until #20 is implemented. In any case, it's still useful as a fallback when MATH fonts are absent.

**Comment by rwlbuis** [comment]
For BlinkOn presentation it was decided to show basic roots using PaintNG, which is now implemented. Long term it still seems best to use the radical symbol.

**Comment by fred-wang** [comment]
I think this is essentially fixed although we need more tests.

We currently pass the only one:
https://w3c-test.org/mathml/presentation-markup/radicals/root-parameters-1.html
