### ISSUE TITLE
MathML in SVG foreignObject

### ISSUE THREAD

**Issue by fred-wang** [Igalia/chromium-dev#28]
It is currently possible to embed MathML in SVG foreignObject, and very basic text rendering works. However, the NG layout does not seem to actually be performed so the MathML is not properly rendered. In particular this is causing a crash with the following test case because because CurrentFragment() is null when  LayoutNGMathMLFraction::Paint is called in the following example:  

    <svg style="font-size: 15pt" xmlns="http://www.w3.org/2000/svg" width="400px" height="220px" viewBox="0 0 200 110">
      <g transform="translate(10,80)">
        <path d="M 0 0 L 150 0 A 75 75 0 0 0 0 0                                               M 30 0 L 30 -60 M 30 -10 L 40 -10 L 40 0" fill="none" stroke="black"/>
        <switch transform="translate(40,-50)">
          <foreignObject width="100" height="50" requiredExtensions="http://www.w3.org/1998/Math/MathML"><math><msup><mi>ρ</mi><mfrac><mn>1</mn><mn>2</mn></mfrac></msup></math></foreignObject>
          <text>ρ^(1/2)</text>
        </switch>
        <switch transform="translate(5,0)">
          <foreignObject width="100" height="50" requiredExtensions="http://www.w3.org/1998/Math/MathML"><math><mrow><mn>1</mn></mrow></math>
          </foreignObject>
          <text>1</text>
        </switch>
        <switch transform="translate(80,0)">
          <foreignObject width="100" height="50" requiredExtensions="http://www.w3.org/1998/Math/MathML"><math><mrow><mi>ρ</mi></mrow></math></foreignObject>
          <text>ρ</text>
        </switch>
      </g>
    </svg>

Even if you remove the fraction, other issues may happen e.g. crash when you click/select the text nodes.

I'm not sure LayoutNG (e.g. HTML div) in foreignObject has actually ever happened with the upstream code.

**Comment by rwlbuis** [comment]
The patch to disable LayoutNG for foreignObject is here:
https://chromium-review.googlesource.com/1133164

**Comment by fred-wang** [comment]
https://github.com/Igalia/chromium-dev/commit/b0ae1bde0a5cbf6c916d989b2697202d9e785539 prevents the crash. Now legacy mathml layout will be used i.e. no specific rendering at all. It seems the proper solution would be to implement LayoutNGforeignObject per the code comments.

**Comment by fred-wang** [comment]
Trying in content_shell, these pages with mathml in svg no longer crash:
http://frederic-wang.fr/opentype-math-in-harfbuzz.html
http://www.mathml-association.org/MathMLinHTML5/S3.html

**Comment by fred-wang** [comment]
Tests:
https://w3c-test.org/mathml/relations/html5-tree/integration-point-4.html (currently fails because of this bug)
https://w3c-test.org/mathml/relations/html5-tree/required-extensions-2.html
https://w3c-test.org/mathml/relations/html5-tree/integration-point-1.html

**Comment by fred-wang** [comment]
I moved this issue to upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=989916 since it's not independent from MathML.
