### ISSUE TITLE
Crash with table and mrow

### ISSUE THREAD

**Issue by fred-wang** [Igalia/chromium-dev#40]
cc @rwlbuis @bkardell

Crashtest:

        data:text/html,<math><mrow><mtable></mtable></mrow></math>

This happens with https://w3c-test.org/mathml/presentation-markup/spaces/space-like-003.html so chrome lacks several WPT results.

**Comment by rwlbuis** [comment]
This should now be fixed, it was due to the assumption table was a valid LayoutNGMathMLBlock.
