### ISSUE TITLE
FATAL: Check failed: is_self_collapsing.

### ISSUE THREAD

**Issue by fred-wang** [Igalia/chromium-dev#46]
Minimal testcase:

    data:text/html,<math style="overflow: visible" display="block">

Currently mathml.css has a rule to force overflow: hidden and workaround that issue. One can easily fix the issue by making that rule !important but we should really understand what's happening. 

    math[display="block" i] {
        display: block;
        text-align: center;
        /* This forces a new block formatting context to workaround an assertion in
           debug mode. TODO(fwang): Analyze this more carefully... */
        overflow: hidden;
    }

Backtrace does not contain anything related to math:

    [11845:11845:0805/180930.385947:FATAL:ng_block_layout_algorithm.cc(1402)] Check failed: is_self_collapsing. 
    #0 0x55865d07f9e9 base::debug::CollectStackTrace()
    #1 0x55865cfbb313 base::debug::StackTrace::StackTrace()
    #2 0x55865cfd0ea3 logging::LogMessage::~LogMessage()
    #3 0x55865fd3b1ad blink::NGBlockLayoutAlgorithm::FinishInflow()
    #4 0x55865fd3abbd blink::NGBlockLayoutAlgorithm::HandleInflow()
    #5 0x55865fd32e37 blink::NGBlockLayoutAlgorithm::Layout()
    #6 0x55865fd31d1a blink::NGBlockLayoutAlgorithm::Layout()
    #7 0x55865fd09e93 _ZN5blink12_GLOBAL__N_121CreateAlgorithmAndRunINS_22NGBlockLayoutAlgorithmEZNS0_19LayoutWithAlgorithmERKNS_23NGLayoutAlgorithmParamsEEUlPNS_27NGLayoutAlgorithmOperationsEE_EEvS5_RKT0_
    #8 0x55865fd09a1a _ZN5blink12_GLOBAL__N_124DetermineAlgorithmAndRunIZNS0_19LayoutWithAlgorithmERKNS_23NGLayoutAlgorithmParamsEEUlPNS_27NGLayoutAlgorithmOperationsEE_EEvS4_RKT_
    #9 0x55865fd0289b blink::NGBlockNode::Layout()
    #10 0x55865fd3aaeb blink::NGBlockLayoutAlgorithm::HandleInflow()
    #11 0x55865fd32e37 blink::NGBlockLayoutAlgorithm::Layout()
    #12 0x55865fd31d1a blink::NGBlockLayoutAlgorithm::Layout()
    #13 0x55865fd09e93 _ZN5blink12_GLOBAL__N_121CreateAlgorithmAndRunINS_22NGBlockLayoutAlgorithmEZNS0_19LayoutWithAlgorithmERKNS_23NGLayoutAlgorithmParamsEEUlPNS_27NGLayoutAlgorithmOperationsEE_EEvS5_RKT0_
    #14 0x55865fd09a1a _ZN5blink12_GLOBAL__N_124DetermineAlgorithmAndRunIZNS0_19LayoutWithAlgorithmERKNS_23NGLayoutAlgorithmParamsEEUlPNS_27NGLayoutAlgorithmOperationsEE_EEvS4_RKT_
    #15 0x55865fd0289b blink::NGBlockNode::Layout()
    #16 0x55865fcf2595 blink::LayoutNGBlockFlow::UpdateBlockLayout()
    #17 0x55865fb38c49 blink::LayoutBlock::UpdateLayout()
    #18 0x55865fb4d803 blink::LayoutBlockFlow::PositionAndLayoutOnceIfNeeded()
    #19 0x55865fb4dddf blink::LayoutBlockFlow::LayoutBlockChild()
    #20 0x55865fb4c5ac blink::LayoutBlockFlow::LayoutBlockChildren()
    #21 0x55865fb4a781 blink::LayoutBlockFlow::LayoutChildren()
    #22 0x55865fb49c40 blink::LayoutBlockFlow::UpdateBlockLayout()
    #23 0x55865fc8b150 blink::LayoutView::UpdateBlockLayout()
    #24 0x55865fb38c49 blink::LayoutBlock::UpdateLayout()
    #25 0x55865fc8b3b1 blink::LayoutView::UpdateLayout()

**Comment by rwlbuis** [comment]
This should be fixed now.
