### ISSUE TITLE
FATAL: Security DCHECK failed: !NeedsLayout() || LayoutBlockedByDisplayLock(DisplayLockContext::kChildren). 

### ISSUE THREAD

**Issue by fred-wang** [Igalia/chromium-dev#47]
Found with the test https://github.com/web-platform-tests/wpt/pull/18293

Minimal repro:

      <math><mi><span>a</span><span style="position: absolute">a</span></mi></math>

It seems token elements do not layout out-of-flow positioned children. Backtrace:

    5:5:0806/134818.645814:INFO:layout_object.cc(4102)] 
    LayoutView 0x1e655c204010              	#document
      LayoutNGBlockFlow 0x1e655c224010     	HTML
        LayoutNGBlockFlow 0x1e655c224150   	BODY
          LayoutNGMathMLBlock 0x1e655c224290	math
            LayoutNGMathMLToken 0x1e655c2243d0	mi
              LayoutInline 0x1e655c234010  	SPAN
                LayoutText 0x1e655c238010  	#text "a"
    *         LayoutNGBlockFlow (positioned) 0x1e655c224510	SPAN style="position: absolute"
                LayoutText 0x1e655c2380f0  	#text "a"
          LayoutText 0x1e655c2381d0        	#text "\n"
    [5:5:0806/134818.646017:FATAL:layout_object.h(424)] Security DCHECK failed: !NeedsLayout() || LayoutBlockedByDisplayLock(DisplayLockContext::kChildren). 
    #0 0x55dee99339e9 base::debug::CollectStackTrace()
    #1 0x55dee986f313 base::debug::StackTrace::StackTrace()
    #2 0x55dee9884ea3 logging::LogMessage::~LogMessage()
    #3 0x55deebf7c62a blink::LayoutObject::AssertLaidOut()
    #4 0x55deebf6f288 blink::LocalFrameView::UpdateLayout()
    #5 0x55deebbfcd27 blink::Document::ImplicitClose()
    #6 0x55deebbfd005 blink::Document::CheckCompletedInternal()
    #7 0x55deebbfcade blink::Document::CheckCompleted()

**Comment by fred-wang** [comment]
We should probably do something like in WebKit: call InsertPositionedObject to insert OOF children into their containing block (we haven't decided yet in https://github.com/mathml-refresh/mathml/issues/16 but for now we can say it is the parent itself) and call LayoutPositionedObjects for all mathml layout. Maybe functions are different in LayoutNG.

**Comment by rwlbuis** [comment]
This should be fixed now. NGOutOfFlowLayoutPart seems to be the API we needed to call.
