### ISSUE TITLE
[FATAL:layout_block_flow.cc(4889)] Check failed: !IsLayoutNGObject(). 

### ISSUE THREAD

**Issue by fred-wang** [Igalia/chromium-dev#48]
This is related to what @javifernandez  is working on (I can't find his CL for GridNG)

Just put the `<math>` as a grid item:

       <div style="display: grid"><math>

Backtrace:

    [5:5:0806/181405.865782:FATAL:layout_block_flow.cc(4889)] Check failed: !IsLayoutNGObject(). 
    #0 0x55dd58c86a29 base::debug::CollectStackTrace()
    #1 0x55dd58bc2353 base::debug::StackTrace::StackTrace()
    #2 0x55dd58bd7ee3 logging::LogMessage::~LogMessage()
    #3 0x55dd5b7514ab blink::LayoutBlockFlow::ClearOffsetMappingIfNeeded()
    #4 0x55dd5b750af7 blink::LayoutBlockFlow::UpdateBlockLayout()
    #5 0x55dd5b73fc89 blink::LayoutBlock::UpdateLayout()
    #6 0x55dd5d0a2ca8 blink::GridTrackSizingAlgorithmStrategy::LogicalHeightForChild()
    #7 0x55dd5d0a5eeb blink::IndefiniteSizeStrategy::MinContentForChild()
    #8 0x55dd5d0a31a3 blink::GridTrackSizingAlgorithmStrategy::MinSizeForChild()
    #9 0x55dd5d0a6c74 blink::GridTrackSizingAlgorithm::SizeTrackToFitNonSpanningItem()
    #10 0x55dd5d0a7335 blink::GridTrackSizingAlgorithm::ResolveIntrinsicTrackSizes()
    #11 0x55dd5d0ac0f5 blink::GridTrackSizingAlgorithm::Run()
    #12 0x55dd5b7d74f8 blink::LayoutGrid::ComputeTrackSizesForIndefiniteSize()
    #13 0x55dd5b7d6171 blink::LayoutGrid::UpdateBlockLayout()
    #14 0x55dd5b73fc89 blink::LayoutBlock::UpdateLayout()
    #15 0x55dd5b90a76e blink::NGBlockNode::RunLegacyLayout()
    #16 0x55dd5b909495 blink::NGBlockNode::Layout()
    #17 0x55dd5b93f92e blink::NGBlockLayoutAlgorithm::LayoutNewFormattingContext()
    #18 0x55dd5b93dc53 blink::NGBlockLayoutAlgorithm::HandleNewFormattingContext()

**Comment by fred-wang** [comment]
A get the same assert when `<math>` is used as a flex item with legacy flexbox layout:

    <div style="display: flex"><math>

Backtrace:

    [5:5:0806/182539.554674:FATAL:layout_block_flow.cc(4889)] Check failed: !IsLayoutNGObject(). 
    #0 0x561e84ecba29 base::debug::CollectStackTrace()
    #1 0x561e84e07353 base::debug::StackTrace::StackTrace()
    #2 0x561e84e1cee3 logging::LogMessage::~LogMessage()
    #3 0x561e879964ab blink::LayoutBlockFlow::ClearOffsetMappingIfNeeded()
    #4 0x561e87995af7 blink::LayoutBlockFlow::UpdateBlockLayout()
    #5 0x561e87984c89 blink::LayoutBlock::UpdateLayout()
    #6 0x561e87a0e9ed blink::LayoutFlexibleBox::LayoutLineItems()
    #7 0x561e87a0a87f blink::LayoutFlexibleBox::LayoutFlexItems()
    #8 0x561e87a0a0e5 blink::LayoutFlexibleBox::UpdateBlockLayout()

However, no problem if I enable LayoutNGFlexBox :

        LayoutNGBlockFlow {BODY} at (8,8) size 784x584
          LayoutNGFlexibleBox {DIV} at (0,0) size 784x0
            LayoutNGMathMLBlock {math} at (0,0) size 0x0

No I don't get this problem either with tables, since the math is wrapped into a LayoutNGTableCell:

    <div style="display: table"><math>

    LayoutNGBlockFlow {BODY} at (8,8) size 784x584
      LayoutTable {DIV} at (0,0) size 0x0
        LayoutTableSection (anonymous) at (0,0) size 0x0
          LayoutTableRow (anonymous) at (0,0) size 0x0
            LayoutNGTableCell (anonymous) at (0,0) size 0x0 [r=0 c=0 rs=1 cs=1]
              LayoutNGMathMLBlock {math} at (0,0) size 0x0

**Comment by rwlbuis** [comment]
I can't reproduce this (anymore).

**Comment by fred-wang** [comment]
@rwlbuis Can you dump the layout tree with ./content_shell --run-web-tests ? I suspect this was fixed by https://github.com/Igalia/chromium-dev/commit/7c069978508c0b2fdbb622bbbcfa783e4062a854

**Comment by rwlbuis** [comment]
layout tree dump:
  LayoutNGBlockFlow {HTML} at (0,0) size 800x600
    LayoutNGBlockFlow {BODY} at (8,8) size 784x584
      LayoutGrid {DIV} at (0,0) size 784x0
        LayoutNGMathMLBlock {math} at (0,0) size 784x0
